import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavComponent from "./components/NavComponent";
import NavMobileComponent from "./components/NavMobileComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Nav móvil (XS-SM) */}
        <div className="md:hidden sticky top-0 z-50">
          <NavMobileComponent />
        </div>
        {/* Nav desktop (MD en adelante) */}
        <div className="hidden md:block sticky top-0 z-50">
          <NavComponent />
        </div>
        {children}
      </body>
    </html>
  );
}
