# Generated by Django 5.2.5 on 2025-10-10 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_delete_task_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='base_price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Precio del plan sin tasas', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plan',
            name='fee_cents',
            field=models.PositiveIntegerField(default=35000, help_text='Tasa USPTO u otra, en centavos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
