# Generated by Django 5.2.5 on 2025-10-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
