# Generated by Django 5.2.5 on 2025-11-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_trademark_and_user_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trademarkevidence',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='trademarkevidence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
