# Generated by Django 5.2.5 on 2025-11-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_trademarkevidence_options_and_more'),
        ('core', '0008_password_reset_code'),
    ]

    operations = [
    ]
