"""
Django settings for marcasoon project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from datetime import timedelta

# Helper to read env vars (supports python-decouple if installed)
try:
    from decouple import config as _decouple_config
    def _cfg(k, default=None, cast=None):
        return _decouple_config(k, default=default, cast=cast)
except Exception:
    def _cfg(k, default=None, cast=None):
        v = os.getenv(k, default)
        if v is None:
            return v
        if cast:
            try:
                return cast(v)
            except Exception:
                return default
        return v

try:
    from corsheaders.defaults import default_headers
except Exception:
    default_headers = (
        'accept', 'accept-encoding', 'authorization', 'content-type', 'dnt', 'origin', 'user-agent',
        'x-csrftoken', 'x-requested-with'
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _cfg('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Parse DJANGO_DEBUG to a real boolean (defaults to False in production).
DEBUG = _cfg('DJANGO_DEBUG', 'False', cast=bool)

ALLOWED_HOSTS = ['marcasoon-webapp.onrender.com', 'localhost', '127.0.0.1', '72.60.115.239', 'marcasoon.com']

RENDER_EXTERNAL_HOSTNAME = _cfg('RENDER_EXTERNAL_HOSTNAME', 'marcasoon-webapp.onrender.com')

# Cookies/CSRF defaults (override below in DEBUG for local dev)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'core'
]

# Use custom user model from core app
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marcasoon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marcasoon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _cfg('DB_NAME', 'marcasoon_db'),
        'USER': _cfg('DB_USER', 'marcasoon_user'),
        'PASSWORD': _cfg('DB_PASSWORD'),
        'HOST': _cfg('DB_HOST', 'localhost'),
        'PORT': _cfg('DB_PORT', '5432'),
    }
}


# USPTO / api.data.gov configuration
USPTO_TSDR__BASE = 'https://tsdr.uspto.gov'
USPTO_API_BASE = 'https://api.uspto.gov'  # JSON (via api.data.gov)
USPTO_API_KEY = _cfg('USPTO_API_KEY')
# Optional specific endpoints (set them in your environment once you pick endpoints from docs)

# Trademark Lookup (RapidAPI)
TRADEMARK_LOOKUP_API_BASE = 'https://trademark-lookup-api.p.rapidapi.com'
# Move this key to environment var in production: os.getenv('TRADEMARK_LOOKUP_API_KEY')
TRADEMARK_LOOKUP_API_KEY = _cfg('TRADEMARK_LOOKUP_API_KEY')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL base for static assets
STATIC_URL = '/static/'

# Always set STATIC_ROOT so collectstatic has a destination both in dev and prod
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use optimized storage in non-debug (production)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Optional: local source directory for static assets (if you place app-level or project-level static/)
# STATICFILES_DIRS = [BASE_DIR / 'static']

# Note: This project previously had STATIC_MEDIA_ROOT; Django ignores it. Keeping media config below.

# Media files (for uploads like logos and sounds)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#CORS AUTHORIZATION
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://marcasoon-webapp.onrender.com",
    "https://marcasoon.netlify.app",
    "http://72.60.115.239",
]
CORS_ALLOW_CREDENTIALS = True

# Allow Netlify preview deploys like https://<hash>--marcasoon.netlify.app
CORS_ALLOWED_ORIGIN_REGEXES = [r"^https://([a-z0-9-]+\.)*netlify\.app$"]

# Allow browser Client Hints headers used by Chrome (sec-ch-ua*) in preflight
CORS_ALLOW_HEADERS = list(default_headers) + [
    'sec-ch-ua',
    'sec-ch-ua-mobile',
    'sec-ch-ua-platform',
]

# Stripe configuration
STRIPE_PUBLIC_KEY = _cfg('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = _cfg('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = _cfg('STRIPE_WEBHOOK_SECRET', '')
STRIPE_CURRENCY = _cfg('STRIPE_CURRENCY', 'usd')
FRONTEND_URL = _cfg('FRONTEND_URL', 'http://localhost:3000')

# Paypal configuration
PAYPAL_CLIENT_ID = _cfg('PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = _cfg('PAYPAL_CLIENT_SECRET')
PAYPAL_MODE = _cfg('PAYPAL_MODE', 'sandbox')  # 'live' en producción


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # JWT-only for APIs: disables SessionAuthentication to avoid CSRF on DRF views
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# CSRF trusted origins (production + local)
CSRF_TRUSTED_ORIGINS = [
    'https://marcasoon-webapp.onrender.com',
    'https://marcasoon.netlify.app',
    'https://marcasoon.com',
    'http://72.60.115.239',
]

# Developer-friendly overrides for local HTTP testing
if DEBUG:
    # Allow local hosts
    ALLOWED_HOSTS = ['marcasoon-webapp.onrender.com', 'localhost', '127.0.0.1', '72.60.115.239', 'marcasoon.com']
    # When testing over http://, secure cookies are not sent; relax for dev
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # Lax is enough for same-site form login; use None+Secure only when on HTTPS and cross-site is needed
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    # Add local origins for CSRF in development
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'https://marcasoon-webapp.onrender.com',
        'https://marcasoon.netlify.app'
    ]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=480),  # p.ej. 480 min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # p.ej. 7 días
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    # otras opciones según necesites…
}


# Email configuration (use python-decouple if available; otherwise fallback to env vars)
EMAIL_BACKEND = 'core.email_backend.IPv4EmailBackend'
EMAIL_HOST = _cfg('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(_cfg('EMAIL_PORT', 465))
EMAIL_HOST_USER = _cfg('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = _cfg('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
# Use the authenticated account as default sender if not explicitly configured
DEFAULT_FROM_EMAIL = _cfg('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
# Where contact form emails should be delivered (defaults to EMAIL_HOST_USER or DEFAULT_FROM_EMAIL)
CONTACT_RECEIVER_EMAIL = _cfg('CONTACT_RECEIVER_EMAIL', EMAIL_HOST_USER or DEFAULT_FROM_EMAIL)

# Webinar embed configuration: public page will iframe this URL
# Example: https://www.youtube.com/embed/<video_id>?autoplay=1 or a Vimeo/Zoom embed
WEBINAR_EMBED_URL = _cfg('WEBINAR_EMBED_URL', 'https://www.youtube.com/embed/sNSwSrASlrM?autoplay=1')